# AFL Model - Part 4 - Weekly Predictions
Now that we have explored different algorithms for modelling, we can implement our chosen model and predict this week's AFL games! All you need to do is run the afl_modelling script each Thursday or Friday to predict the following week's games.

In [57]:
# Import Modules
from afl_feature_creation import prepare_afl_features
import afl_data_cleaning
import afl_feature_creation
import afl_modelling
import datetime
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
from sklearn import svm, tree, linear_model, neighbors, naive_bayes, ensemble, discriminant_analysis, gaussian_process
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB

## Creating The Features For This Weekend's Games
To actually predict this weekend's games, we need to create the same features that we have created in the previous tutorials for the games that will be played this weekend. This includes all the rolling averages, efficiency features, elo features etc. So the majority of this tutorial will be using previously defined functions to create features for the following weekend's games.

### Create Next Week's DataFrame
Let's first get our cleaned afl_data dataset, as well as the odds for next weekend and the 2018 fixture.

In [58]:
# Grab the cleaned AFL dataset and the column order
afl_data = afl_data_cleaning.prepare_afl_data()
ordered_cols = afl_data.columns

# Define a function which grabs the odds for each game for the following weekend
def get_next_week_odds(path):
    # Get next week's odds
    next_week_odds = pd.read_csv(path)
    next_week_odds = next_week_odds.rename(columns={"team_1": "home_team", 
                                                "team_2": "away_team", 
                                                "team_1_odds": "odds", 
                                                "team_2_odds": "odds_away"
                                               })
    return next_week_odds

# Import the fixture
# Define a function which gets the fixture and cleans it up
def get_fixture(path):
    # Get the afl fixture
    fixture = pd.read_csv(path)

    # Replace team names and reformat
    fixture = fixture.replace({'Brisbane Lions': 'Brisbane', 'Footscray': 'Western Bulldogs'})
    fixture['Date'] = pd.to_datetime(fixture['Date']).dt.date.astype(str)
    fixture = fixture.rename(columns={"Home.Team": "home_team", "Away.Team": "away_team"})
    return fixture

next_week_odds = get_next_week_odds("data/weekly_odds.csv")
fixture = get_fixture("data/afl_fixture_2018.csv")

In [59]:
fixture.tail()

,Date,Season,Season.Game,Round,home_team,away_team,Venue
211,2018-08-24,2018,212,NaN,Brisbane,West Coast,Gabba
212,2018-08-24,2018,213,NaN,Carlton,St Kilda,Etihad Stadium
213,2018-08-24,2018,214,NaN,Richmond,Melbourne,MCG
214,2018-08-24,2018,215,NaN,Port Adelaide,Essendon,Adelaide Oval
215,2018-08-24,2018,216,NaN,Fremantle,Collingwood,Optus Stadium

Now that we have these DataFrames, we will define a function which combines the fixture and next week's odds to create a single DataFrame for the games over the next 7 days. To use this function we will need Game IDs for next week. So we will create another function which creates Game IDs by using the Game ID from the last game played and adding 1 to it.

In [60]:
# Define a function which creates game IDs for this week's footy games
def create_next_weeks_game_ids(afl_data):
    odds = get_next_week_odds("data/weekly_odds.csv")

    # Get last week's Game ID
    last_afl_data_game = afl_data['Game'].iloc[-1]

    # Create Game IDs for next week
    game_ids = [(i+1) + last_afl_data_game for i in range(odds.shape[0])]
    return game_ids

# Define a function which creates this week's footy game DataFrame
def get_next_week_df(afl_data):
    # Get the fixture and the odds for next week's footy games
    fixture = get_fixture("data/afl_fixture_2018.csv")
    next_week_odds = get_next_week_odds("data/weekly_odds.csv")
    next_week_odds['Game'] = create_next_weeks_game_ids(afl_data)

    # Get today's date and next week's date and create a DataFrame for next week's games
    todays_date = datetime.datetime.today().strftime('%Y-%m-%d')
    date_in_7_days = (datetime.datetime.today() + datetime.timedelta(days=7)).strftime('%Y-%m-%d')
    fixture = fixture[(fixture['Date'] >= todays_date) & (fixture['Date'] < date_in_7_days)].drop(columns=['Season', 'Season.Game', 'Round'])
    next_week_df = pd.merge(fixture, next_week_odds, on=['home_team', 'away_team'])

    # Split the DataFrame onto two rows for each game
    h_df = next_week_df[['Date', 'Game', 'home_team', 'away_team', 'odds']]
    h_df['Team'] = h_df['home_team']
    h_df['Opposition'] = h_df['away_team']
    h_df['Home?'] = 1
    a_df = next_week_df[['Date', 'Game', 'home_team', 'away_team', 'odds_away']].rename(columns={'odds_away': 'odds'})
    a_df['Team'] = a_df['away_team']
    a_df['Opposition'] = a_df['home_team']
    a_df['Home?'] = 0
    next_week = a_df.append(h_df).sort_values(by='Game')
    return next_week

In [61]:
next_week_df = get_next_week_df(afl_data)
game_ids_next_round = create_next_weeks_game_ids(afl_data)
next_week_df.head()

,Date,Game,home_team,away_team,odds,Team,Opposition,Home?
0,2018-07-27,15354,Essendon,Sydney,2.22,Sydney,Essendon,0
0,2018-07-27,15354,Essendon,Sydney,1.81,Essendon,Sydney,1
1,2018-07-28,15355,Richmond,Collingwood,3.65,Collingwood,Richmond,0
1,2018-07-28,15355,Richmond,Collingwood,1.38,Richmond,Collingwood,1
2,2018-07-28,15356,Geelong,Brisbane,5.80,Brisbane,Geelong,0

### Create Each Feature
Now let's append next week's DataFrame to our afl_data DataFrame and then create all the features we used in the [AFL Feature Creation Tutorial](0.2. afl_feature_creation_tutorial.ipynb).

In [62]:
# Append next week's games to our afl_data DataFrame
afl_data = afl_data.append(next_week_df).reset_index(drop=True)
afl_data = afl_data[ordered_cols]

# Create disposal efficiency column
afl_data['disposal_efficiency'] = afl_data['ED'] / afl_data['D']

# Create rolling averages for our statistics
cols_indx_start = afl_data.columns.get_loc("GA")
afl_avgs = afl_feature_creation.create_rolling_averages(afl_data, 6, afl_data.columns[cols_indx_start:])

# Create form between teams feature
afl_avgs = afl_feature_creation.form_between_teams(afl_avgs, 6)

# Apply elos
elos, probs, elo_dict = afl_feature_creation.elo_applier(afl_data, 24)
afl_avgs['home_elo'] = afl_avgs['Game'].map(elos).str[0]
afl_avgs['away_elo'] = afl_avgs['Game'].map(elos).str[1]

# Get elos for next week
afl_avgs.loc[afl_avgs['home_elo'].isna(), 'home_elo'] = afl_avgs[afl_avgs['home_elo'].isna()]['home_team'].map(elo_dict)
afl_avgs.loc[afl_avgs['away_elo'].isna(), 'away_elo'] = afl_avgs[afl_avgs['away_elo'].isna()]['away_team'].map(elo_dict)

# Create Adjusted Margin and then Average it over a 6 game window
afl_avgs = afl_feature_creation.map_elos(afl_avgs)
afl_avgs['Adj_elo_ave_margin'] = afl_avgs['Margin'] * afl_avgs['elo_Opp'] / afl_avgs['elo']
afl_avgs = afl_feature_creation.create_rolling_averages(afl_avgs, 6, ['Adj_elo_ave_margin'])

# Create average elo of opponents beaten/lost to feature
afl_avgs = afl_feature_creation.create_ave_elo_opponent(afl_avgs, 6, beaten_or_lost='beaten')
afl_avgs = afl_feature_creation.create_ave_elo_opponent(afl_avgs, 6, beaten_or_lost='lost')

# Create regular margin rolling average
afl_avgs = afl_feature_creation.create_rolling_averages(afl_avgs, 6, ['Margin'])
afl_avgs.tail()

,Team,odds,Date,home_team,away_team,Behinds,Game,Goals,Home?,Opposition,Opposition Behinds,Opposition Goals,Opposition Points,Points,Round,Venue,Season,Status,GA_ave_6,CP_ave_6,UP_ave_6,ED_ave_6,CM_ave_6,MI5_ave_6,One.Percenters_ave_6,BO_ave_6,K_ave_6,HB_ave_6,D_ave_6,M_ave_6,G_ave_6,B_ave_6,T_ave_6,HO_ave_6,I50_ave_6,CL_ave_6,CG_ave_6,R50_ave_6,FF_ave_6,FA_ave_6,AF_ave_6,SC_ave_6,CCL_ave_6,SCL_ave_6,SI_ave_6,MG_ave_6,TO_ave_6,ITC_ave_6,T5_ave_6,disposal_efficiency_ave_6,form_over_opposition_6,home_elo,away_elo,elo,elo_Opp,Adj_elo_ave_margin_ave_6,average_elo_opponents_beaten_6,average_elo_opponents_lost_6,Margin_ave_6
2991,North Melbourne,2.24,2018-07-29,North Melbourne,West Coast,NaN,15360,NaN,1,West Coast,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.333333,153.833333,208.333333,248.666667,12.666667,10.333333,47.666667,4.166667,188.333333,167.666667,356.000000,76.833333,12.666667,7.500000,62.833333,43.833333,49.833333,37.000000,58.166667,34.833333,23.666667,19.166667,1475.666667,1599.000000,13.833333,23.166667,83.333333,5378.166667,71.333333,71.833333,12.333333,0.697811,2,1455.951333,1608.670838,1455.951333,1608.670838,-1.228836,1520.030707,1510.560437,-1.500000
2992,Port Adelaide,1.40,2018-07-29,Western Bulldogs,Port Adelaide,NaN,15361,NaN,0,Western Bulldogs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.833333,149.500000,227.333333,260.166667,12.000000,12.500000,58.666667,7.833333,219.666667,155.000000,374.666667,92.833333,11.833333,9.166667,75.666667,43.666667,55.666667,38.000000,54.500000,37.166667,22.333333,21.666667,1631.333333,1734.833333,11.500000,26.500000,87.833333,5844.166667,74.000000,72.666667,17.000000,0.693819,4,1444.908908,1555.644928,1555.644928,1444.908908,13.767518,1400.051819,1549.380494,15.500000
2993,Western Bulldogs,3.50,2018-07-29,Western Bulldogs,Port Adelaide,NaN,15361,NaN,1,Port Adelaide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.666667,137.833333,236.666667,274.833333,8.833333,8.666667,51.000000,6.666667,193.666667,178.666667,372.333333,81.000000,10.500000,6.666667,60.833333,30.000000,50.000000,32.666667,51.333333,35.166667,21.000000,19.666667,1486.333333,1546.166667,10.666667,22.000000,72.833333,5311.000000,71.666667,69.833333,13.166667,0.736290,2,1444.908908,1555.644928,1444.908908,1555.644928,-39.749007,1412.598306,1530.718856,-37.333333
2994,Hawthorn,1.49,2018-07-29,Fremantle,Hawthorn,NaN,15362,NaN,0,Fremantle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.500000,138.333333,257.666667,300.333333,10.000000,15.333333,54.833333,8.500000,216.333333,177.500000,393.833333,96.833333,14.000000,11.000000,69.833333,41.833333,55.333333,35.000000,54.833333,30.000000,21.166667,22.500000,1664.333333,1748.000000,11.166667,23.833333,109.666667,5686.500000,67.833333,70.000000,11.500000,0.762053,5,1433.532137,1583.250525,1583.250525,1433.532137,29.785442,1425.041690,1442.747111,33.333333
2995,Fremantle,2.96,2018-07-29,Fremantle,Hawthorn,NaN,15362,NaN,1,Hawthorn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.333333,136.000000,216.833333,248.500000,7.500000,9.333333,47.500000,2.666667,200.166667,148.666667,348.833333,83.333333,9.333333,6.166667,71.166667,39.666667,45.666667,32.333333,55.500000,39.000000,20.333333,19.833333,1495.166667,1588.833333,11.166667,21.166667,78.833333,5227.000000,75.000000,70.666667,10.166667,0.712289,1,1433.532137,1583.250525,1433.532137,1583.250525,-20.097757,1442.470402,1545.516748,-17.333333

Our DataFrame looks great! Although there are some NaNs, these are only in columns like 'Goals' which obviously don't have a value yet as the game hasn't been played.

Now we need to get our DataFrame on one line so that each row corresponds to one footy game. Let's use our previously defined function for this. Let's also drop the columns with NaNs which we don't need.

In [63]:
# Get each footy match on individual rows and drop irrelevant columns
one_line = afl_modelling.get_df_on_one_line(afl_avgs)

# Drop duplicate columns and unnecessary columns
cols_to_drop = ['Opposition Behinds', 'Goals', 'Behinds', 'Opposition Goals', 'Opposition Points', 'Points', 'Round', 'Venue', 'Season', 'Status',
               'CCL_ave_6', 'SCL_ave_6', 'SI_ave_6', 'MG_ave_6', 'TO_ave_6', 'ITC_ave_6', 'T5_ave_6', 'elo', 'elo_Opp', 'Behinds_away',
               'Goals_away', 'home_elo_away', 'away_elo_away', 'elo_away', 'elo_Opp_away']
one_line = one_line.drop(columns=cols_to_drop)
# Drop all columns where home_elo or away_elo == 1500 exactly, as this is the first game played
one_line = one_line[(one_line['home_elo'] != 1500) & (one_line['away_elo'] != 1500)]

# Drop Na rows from calculating moving averages
one_line = one_line.dropna(axis=0)

Now let's create our differential_df and then filter out DataFrame to only include this weekend's game, based on the Game IDs we created earlier

In [64]:
diff_df = afl_modelling.get_diff_df(one_line)
diff_df = diff_df.drop(columns=['odds', 'odds_away']).select_dtypes(include=[np.number])
prediction_feature_set = diff_df[diff_df['Game'].isin(game_ids_next_round)].dropna(axis=1)

In [65]:
prediction_feature_set

,Game,home_elo,away_elo,CCL_ave_6_away,SCL_ave_6_away,SI_ave_6_away,MG_ave_6_away,TO_ave_6_away,ITC_ave_6_away,T5_ave_6_away,GA_ave_6_diff,CP_ave_6_diff,UP_ave_6_diff,ED_ave_6_diff,CM_ave_6_diff,MI5_ave_6_diff,One.Percenters_ave_6_diff,BO_ave_6_diff,K_ave_6_diff,HB_ave_6_diff,D_ave_6_diff,M_ave_6_diff,G_ave_6_diff,B_ave_6_diff,T_ave_6_diff,HO_ave_6_diff,I50_ave_6_diff,CL_ave_6_diff,CG_ave_6_diff,R50_ave_6_diff,FF_ave_6_diff,FA_ave_6_diff,AF_ave_6_diff,SC_ave_6_diff,disposal_efficiency_ave_6_diff,form_over_opposition_6_diff,Adj_elo_ave_margin_ave_6_diff,average_elo_opponents_beaten_6_diff,average_elo_opponents_lost_6_diff,Margin_ave_6_diff,implied_odds_prob,implied_odds_prob_away
1517,15354,1511.970228,1647.183809,10.833333,23.333333,75.000000,5940.000000,70.833333,73.000000,10.000000,2.500000,-2.833333,4.500000,-1.833333,3.000000,4.000000,2.666667,4.666667,15.500000,-13.500000,2.000000,13.000000,0.333333,2.833333,7.833333,16.666667,2.666667,6.666667,0.333333,-7.166667,-2.166667,0.666667,107.166667,68.000000,-0.007214,-6,17.796258,33.072288,-53.525168,16.500000,0.552486,0.450450
1518,15355,1616.198957,1509.887844,11.000000,24.500000,105.166667,5857.833333,72.333333,74.666667,9.333333,-2.333333,-1.833333,-54.833333,-60.166667,0.500000,0.666667,0.833333,-0.333333,-19.833333,-37.333333,-57.166667,-15.500000,-0.500000,0.666667,-3.666667,-10.833333,3.500000,-3.000000,2.833333,-3.000000,-7.833333,3.166667,-225.833333,-123.500000,-0.047232,4,-11.807301,115.130679,-10.599178,-12.666667,0.724638,0.273973
1519,15356,1640.811956,1282.932319,12.166667,27.666667,104.500000,5798.833333,67.166667,67.166667,8.500000,-2.833333,4.500000,-12.000000,-20.000000,1.166667,-5.166667,-8.500000,0.500000,-15.666667,5.000000,-10.666667,-16.666667,-2.833333,-0.333333,10.833333,-12.500000,-1.833333,-1.166667,3.833333,-1.666667,-1.000000,2.000000,-80.500000,-111.666667,-0.031488,6,-20.526868,19.820845,-1.136418,-17.833333,0.826446,0.172414
1520,15357,1607.447400,1422.903987,12.666667,24.333333,97.666667,5419.333333,70.500000,67.000000,11.500000,0.666667,17.833333,-47.166667,-32.333333,3.500000,-1.000000,9.166667,1.000000,0.500000,-27.833333,-27.333333,-16.166667,0.666667,1.666667,2.166667,7.333333,2.333333,5.833333,-0.500000,5.000000,-1.333333,2.000000,-88.333333,23.000000,-0.030784,1,14.660369,105.389217,-19.698303,10.666667,0.869565,0.131579
1521,15358,1309.174549,1240.034979,11.833333,19.833333,77.333333,4794.166667,63.666667,59.166667,6.666667,-1.166667,23.666667,-50.500000,-47.500000,-0.166667,-2.000000,14.333333,-2.166667,8.166667,-34.000000,-25.833333,-14.666667,0.333333,3.500000,16.166667,13.833333,10.500000,5.500000,6.000000,4.500000,3.666667,-0.666667,2.166667,22.000000,-0.085574,2,27.166897,-121.597065,50.586069,24.166667,0.729927,0.270270
1522,15359,1636.815798,1492.679506,15.666667,24.333333,126.833333,6318.833333,71.666667,80.166667,15.166667,-5.333333,-18.000000,-39.500000,-42.666667,-1.500000,-4.000000,-5.000000,0.833333,-4.333333,-48.666667,-53.000000,-5.500000,-6.166667,-1.166667,-8.500000,-12.333333,-13.833333,-2.166667,-7.333333,5.833333,-1.500000,-3.666667,-201.833333,-159.500000,-0.014588,0,-55.311224,-6.122336,-118.006247,-55.333333,0.568182,0.434783
1523,15360,1455.951333,1608.670838,11.166667,23.500000,85.166667,5550.666667,69.166667,71.333333,9.000000,1.500000,17.333333,-9.000000,-12.000000,0.666667,-0.500000,-1.333333,0.333333,-34.666667,38.666667,4.000000,-24.833333,1.833333,-1.333333,-3.166667,0.333333,-1.500000,2.333333,4.500000,-1.500000,-0.833333,-2.333333,-97.666667,-33.166667,-0.041308,-2,-8.882212,-9.138901,-107.690508,-10.000000,0.446429,0.555556
1524,15361,1444.908908,1555.644928,11.500000,26.500000,87.833333,5844.166667,74.000000,72.666667,17.000000,-2.166667,-11.666667,9.333333,14.666667,-3.166667,-3.833333,-7.666667,-1.166667,-26.000000,23.666667,-2.333333,-11.833333,-1.333333,-2.500000,-14.833333,-13.666667,-5.666667,-5.333333,-3.166667,-2.000000,-1.333333,-2.000000,-145.000000,-188.666667,0.042471,-2,-53.516525,12.546487,-18.661638,-52.833333,0.285714,0.714286
1525,15362,1433.532137,1583.250525,11.166667,23.833333,109.666667,5686.500000,67.833333,70.000000,11.500000,-3.166667,-2.333333,-40.833333,-51.833333,-2.500000,-6.000000,-7.333333,-5.833333,-16.166667,-28.833333,-45.000000,-13.500000,-4.666667,-4.833333,1.333333,-2.166667,-9.666667,-2.666667,0.666667,9.000000,-0.833333,-2.666667,-169.166667,-159.166667,-0.049764,-4,-49.883199,17.428713,102.769638,-50.666667,0.337838,0.671141

Great! We now have our feature DataFrame for this weekend's games. Let's now model this to create our predictions

## Creating Our Predictions
To create our predictions we will use similar code to what we used in our AFL Modelling Tutorial. We will need to train our model on all the data we have (up until last week's games), and then use our trained model to predict this week. Again, we will use Stacking with XGB, like we did in our AFL Modelling Tutorial.

In [66]:
afl = prepare_afl_features(window=6, k_factor=24).dropna().sort_values(by='Game')
afl = afl_modelling.get_df_on_one_line(afl)

# Drop columns which leak data and which we don't need
dropped_cols = ['Behinds', 'Goals', 'Opposition Behinds', 'Opposition Goals', 'Opposition Points', 'Points',
               'elo', 'elo_Opp', 'CCL_ave_6', 'SCL_ave_6', 'SI_ave_6', 'MG_ave_6', 'TO_ave_6', 'ITC_ave_6', 'T5_ave_6', 'home_win_away',
               'home_elo_away', 'away_elo_away']
afl = afl.drop(columns=dropped_cols)
# Get a differential DataFrame - subtracting the away features from the home features
diff_df = afl_modelling.get_diff_df(afl)

In [67]:
# Hard code estimators from our last tutorial
all_estimators = [
    LogisticRegression(C=0.75, class_weight=None, dual=False, fit_intercept=True,
       intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
       penalty='l2', random_state=None, solver='newton-cg', tol=0.0001,
       verbose=0, warm_start=False),
    
    RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
     max_iter=None, normalize=False, random_state=None, solver='auto',
     tol=0.001),
    
    RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
         max_depth=15, max_features='sqrt', max_leaf_nodes=None,
         min_impurity_decrease=0.0, min_impurity_split=None,
         min_samples_leaf=1, min_samples_split=10,
         min_weight_fraction_leaf=0.0, n_estimators=750, n_jobs=-1,
         oob_score=False, random_state=5, verbose=0, warm_start=False),
    
    GaussianNB(priors=None),
    
    LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
           solver='svd', store_covariance=False, tol=0.0001)
]

# Hard code best cols
best_cols = ['home_elo',
'away_elo',
'GA_ave_6_diff',
'CP_ave_6_diff',
'UP_ave_6_diff',
'ED_ave_6_diff',
'CM_ave_6_diff',
'MI5_ave_6_diff',
'One.Percenters_ave_6_diff',
'BO_ave_6_diff',
'HB_ave_6_diff',
'M_ave_6_diff',
'G_ave_6_diff',
'T_ave_6_diff',
'HO_ave_6_diff',
'I50_ave_6_diff',
'CL_ave_6_diff',
'CG_ave_6_diff',
'R50_ave_6_diff',
'FF_ave_6_diff',
'FA_ave_6_diff',
'AF_ave_6_diff',
'SC_ave_6_diff',
'disposal_efficiency_ave_6_diff',
'R50_efficiency_ave_6_diff',
'I50_efficiency_ave_6_diff',
'Adj_elo_ave_margin_ave_6_diff',
'average_elo_opponents_beaten_6_diff',
'average_elo_opponents_lost_6_diff',
'Margin_ave_6_diff',
'implied_odds_prob',
'implied_odds_prob_away']

In [68]:
# Create our train sets
X = diff_df.drop(columns=['home_win']).select_dtypes(include=[np.number])
y = diff_df['home_win']

features = prediction_feature_set.columns

# Predict Next Round
preds_next_round = afl_modelling.implement_xgb_stacking(X[features].drop(columns='Game'), y, 
                                                        prediction_feature_set.drop(columns='Game'), all_estimators)

C:\Users\wardj\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Now that we have our predictions, the final step is to put our predictions into a DataFrame so they're easy on the eye, and our predictions correspond to actual home and away teams rather than Game IDs. This is the final step.

In [69]:
preds_df = pd.DataFrame({
    "Game": prediction_feature_set['Game'],
    "Prediction (home_win)": preds_next_round
})

prediction_feature_set['home_odds'] = 1 / prediction_feature_set['implied_odds_prob']
prediction_feature_set['away_odds'] = 1 / prediction_feature_set['implied_odds_prob_away']

final_preds_df = pd.merge(preds_df, next_week_df[['home_team', 'away_team', 'Game']], on='Game').drop_duplicates()
final_preds_df = pd.merge(final_preds_df, prediction_feature_set[['home_odds', 'away_odds', 'home_elo', 'away_elo', 'Game']], on='Game')
final_preds_df['Predicted Winner'] = final_preds_df.apply(lambda x: x['home_team'] if x['Prediction (home_win)'] == 1 else x['away_team'], axis=1)

In [70]:
final_preds_df[['Game', 'home_team', 'away_team', 'Predicted Winner', 'home_odds', 'away_odds', 'home_elo', 'away_elo']]

,Game,home_team,away_team,Predicted Winner,home_odds,away_odds,home_elo,away_elo
0,15354,Essendon,Sydney,Essendon,1.81,2.22,1511.970228,1647.183809
1,15355,Richmond,Collingwood,Richmond,1.38,3.65,1616.198957,1509.887844
2,15356,Geelong,Brisbane,Geelong,1.21,5.80,1640.811956,1282.932319
3,15357,GWS,St Kilda,GWS,1.15,7.60,1607.447400,1422.903987
4,15358,Gold Coast,Carlton,Gold Coast,1.37,3.70,1309.174549,1240.034979
5,15359,Adelaide,Melbourne,Melbourne,1.76,2.30,1636.815798,1492.679506
6,15360,North Melbourne,West Coast,West Coast,2.24,1.80,1455.951333,1608.670838
7,15361,Western Bulldogs,Port Adelaide,Port Adelaide,3.50,1.40,1444.908908,1555.644928
8,15362,Fremantle,Hawthorn,Hawthorn,2.96,1.49,1433.532137,1583.250525

In [71]:
final_preds_df[['home_team', 'away_team', 'Predicted Winner', 'home_odds', 'away_odds', 'home_elo', 'away_elo']]

,home_team,away_team,Predicted Winner,home_odds,away_odds,home_elo,away_elo
0,Essendon,Sydney,Essendon,1.81,2.22,1511.970228,1647.183809
1,Richmond,Collingwood,Richmond,1.38,3.65,1616.198957,1509.887844
2,Geelong,Brisbane,Geelong,1.21,5.80,1640.811956,1282.932319
3,GWS,St Kilda,GWS,1.15,7.60,1607.447400,1422.903987
4,Gold Coast,Carlton,Gold Coast,1.37,3.70,1309.174549,1240.034979
5,Adelaide,Melbourne,Melbourne,1.76,2.30,1636.815798,1492.679506
6,North Melbourne,West Coast,West Coast,2.24,1.80,1455.951333,1608.670838
7,Western Bulldogs,Port Adelaide,Port Adelaide,3.50,1.40,1444.908908,1555.644928
8,Fremantle,Hawthorn,Hawthorn,2.96,1.49,1433.532137,1583.250525

## Conclusion
Congratulations! You have created AFL predictions for this week. If you are beginner to this, don't be overwhelmed. The process gets easier each time you do it. And it is super rewarding. In future iterations we will update this tutorial to predict actual odds, and then integrate this with Betfair's API so that you can create an automated betting strategy using Machine Learning to create your predictions!